name: Approve by automation

on:
  pull_request:
    types: [opened, reopened]
jobs:
  approve-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'approve a pull request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "approved by automation"